pipeline:
  name: cypress_pipeline_6859d9147fd642f2a7da1b271067e7af
  identifier: cypress_pipeline_6859d9147fd642f2a7da1b271067e7af
  projectIdentifier: cypress_project_5776491c1d33442fbb7a2c95d965afce
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_26f26a09c1024d3fbe3852bfaf0348c4
        identifier: cypress_stage_26f26a09c1024d3fbe3852bfaf0348c4
        tags: {}
        template:
          templateRef: cypress_template_0cfbb8bbbe4a449caaf8c86691372374
          versionLabel: v1
          gitBranch: main-patch
