pipeline:
  name: cypress_pipeline_5dbda02b8a84494b8de53e1576ee3e9c
  identifier: cypress_pipeline_5dbda02b8a84494b8de53e1576ee3e9c
  projectIdentifier: cypress_project_6bcced833ce241359cb742937589b785
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_5a5d62e669a146ec8070650a5c9a0a5e
        identifier: cypress_stage_5a5d62e669a146ec8070650a5c9a0a5e
        tags: {}
        template:
          templateRef: cypress_template_a3e68a336c9f456597a41e559780dba5
          versionLabel: v1
          gitBranch: main
