pipeline:
  name: cypress_pipeline_8e6120429fc444629edd34753cd4a6f0
  identifier: cypress_pipeline_8e6120429fc444629edd34753cd4a6f0
  projectIdentifier: cypress_project_43d07641c02b4376a29b10aeae844f8a
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_aa63134173a2408bac67bf3737d10ed1
        identifier: cypress_stage_aa63134173a2408bac67bf3737d10ed1
        tags: {}
        template:
          templateRef: cypress_template_81f6601b14cd48ae92b53ed85d464c95
          versionLabel: v1
