pipeline:
  name: UI Repo Non Default
  identifier: UI_Repo_Non_Default
  projectIdentifier: Pankaj
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: S1
        identifier: S1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo UI Repo Non Default
                    environmentVariables: []
                    outputVariables: []
                  timeout: <+input>
        tags: {}
