pipeline:
  name: cypress_pipeline_347d3b73d09244e5996df9dcc42c31cb
  identifier: cypress_pipeline_347d3b73d09244e5996df9dcc42c31cb
  projectIdentifier: cypress_project_5972f79b58554ae5aea57899f3426e13
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_bd574b6cf49646949436d4acc1bbad26
        identifier: cypress_stage_bd574b6cf49646949436d4acc1bbad26
        tags: {}
        template:
          templateRef: cypress_template_e680ece1e5ad49d19eedcbde786a3e78
          versionLabel: v1
          gitBranch: main
