pipeline:
  name: cypress_pipeline_5cd3995d9ae74274a079bb450ea64f99
  identifier: cypress_pipeline_5cd3995d9ae74274a079bb450ea64f99
  projectIdentifier: cypress_project_c55cdc3a9fe74d3a824c9b69cf893025
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_abae80a5a32941549c628106b09b5705
        identifier: cypress_stage_abae80a5a32941549c628106b09b5705
        tags: {}
        template:
          templateRef: cypress_template_7df97322dad244049376b9e116356376
          versionLabel: v1
          gitBranch: main
