pipeline:
  name: cypress_pipeline_bc9722e400db462585183d53c6a70598
  identifier: cypress_pipeline_bc9722e400db462585183d53c6a70598
  projectIdentifier: cypress_project_f55a5f05e1e94e1cacabde7b3a88dc81
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cypress_stage_3d39af1e44ec49b18cd69d1ac6d3c83d
        identifier: cypress_stage_3d39af1e44ec49b18cd69d1ac6d3c83d
        tags: {}
        template:
          templateRef: cypress_template_babdd4e26ae54a0282dd5f9cd4f9e0f7
          versionLabel: v1
